server {
    listen 80;
    server_name _;

    # servir estáticos: URL /static/... -> carpeta /staticfiles/...
    location /static/ {
        alias /app/staticfiles/;
        try_files $uri $uri/ =404;
        access_log off;
        expires off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }

    # favicon opcional
    location = /favicon.ico {
        alias /app/staticfiles/favicon.ico;
    }

    # proxy para la aplicación Django (web:8000)
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://web:8000;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    }
}